### ISSUE TITLE
update_header function does not when file extension not specified

### ISSUE THREAD

**Issue by yucelkilic** [myrafproject/myrafproject#14]
Here is the logger output:

[2020-05-26 22:59:17,197, ERROR], [analyse.py, update_header, 584]: [Errno 2] No such file or directory: '/Users/ykilic/Desktop/test/test_flat'

IRAF produces test_flat or bias/dark files with the extension (.fits). So, MYRaf is trying to apply the update_header function on a file without extension.

**Comment by mshemuni** [comment]
This issue solved solved by:
User forced to save file with `fits` extensions. If not MYRaf will add/replace the extension (`fits`)
commit: b1be35cc633c19847816110d28e30552ebf4bd84
