### ISSUE TITLE
'keymap.all_axes is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)': Can't import ginga.

### ISSUE THREAD

**Issue by vbakis** [myrafproject/myrafproject#3]
Selamlar,

Aşağıdaki hata ile ilgili öneriniz var mı?

>python3 main.py
'keymap.all_axes is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)': Can't import ginga.

**Comment by yucelkilic** [comment]
This problem is caused by ginga's _ImageViewMpl.py_ module. Uncomment the following line to resolve this issue in ginga/mplw/ImageViewMpl.py file.

`# rc['keymap.all_axes'] = []       # enable all axes`
