### ISSUE TITLE
Error when executing installation script

### ISSUE THREAD

**Issue by agustrionopj** [myrafproject/myrafproject#4]
I've got this error message when trying to install MyRAF

```
./myraf2.0_install.sh: line 41: unexpected EOF while looking for matching `"'
./myraf2.0_install.sh: line 43: syntax error: unexpected end of file

```
also, I could not find setup.py in MyRAF directory, as stated in installation script

```
echo "Installing MYRaf 2.0..."
cd myrafproject-2.0-beta
sudo python setup.py install
```

**Comment by yucelkilic** [comment]
Sorry for the error. I've fixed it now. If you encounter other problems, please let me know. 

Thank you.
