### ISSUE TITLE
python2.7: can't open file '/usr/share/myraf/main.py': [Errno 13] Permission denied

### ISSUE THREAD

**Issue by yucelkilic** [myrafproject/myrafproject#5]
If you encounter this problem please give the following commands from the terminal.

```
$ sudo chown -R username:username /usr/share/myraf/
$ sudo rm -rf ~/.cache/matplotlib
$ cd 
$ myraf2
```

**Comment by agustrionopj** [comment]
Thanks, I just encounter with this kind of problem. After I did what you wrote above, I have some permission problem with files within ~/.MYraf2
but after I execute 
```
sudo chown -R username:username ~/.MYraf2/*
```
the problem is solved
