### ISSUE TITLE
Installation error -

### ISSUE THREAD

**Issue by vbakis** [myrafproject/myrafproject#5]
Dear colleagues,

I'm having the following message while running the code:

No module named 'ginga.mplw.ImageViewCanvasMpl': Can't import ginga.

and the code stop running. Could you please help fixing this issue?

Thanks,

Volkan Bakış

**Comment by mshemuni** [comment]
Hello sir. This is a known issue. Can you please provide more information?

What OS do you use?
What distribution of Python do you use?
What is the version of the Python interpreter?

## Possible Solution.

### Install the `ginga`:

`pip install ginga`

If it is already installed, please reinstall it.

### Install the `ginga` from source:
https://ginga.readthedocs.io/en/stable/install.html#installation-from-source

**Comment by vbakis** [comment]
Hi,

I use Pardus Linux which uses a Debian based OS.

I use Python 3.9.12.

I do not use a Python interpreter in my linux computer.

I also installed the Ginga from the sourcecode. The Ginga Works fine, so the installation is OK, but the code seems it is not calling it the proper way!

Best wishes,

Volkan

**Comment by mshemuni** [comment]
New MYRaf's installation involves PyPi. This issue ,s no more a thing.
