### ISSUE TITLE
Calibration tasks are not working

### ISSUE THREAD

**Issue by agustrionopj** [myrafproject/myrafproject#6]
I encounter some issues with calibration task in MYRaf. I got error messages:

> due to an error <zerocombine/darkcombine/flatcombine> can not handle this job

When I did it manually using IRAF or PyRAF,  there are no error came up. I set 'ccdtype' in settings > calibration tab empty (the same as parameter in IRAF/PyRAF)

**Comment by yucelkilic** [comment]
Hi,
 
Sorry for the problem. MYRaf is still in the developing stage :/ So, we are trying to develop MYRaf with the help of you. On the other hand, are you trying to calibrate one filter or multi filter? And could you provide MYRaf's Setting > Calibration Tab screenshot? Here are my settings in the attachment.

**Calibration Tab:**
![calibration_tab](https://user-images.githubusercontent.com/1447855/29275273-426c1b18-8113-11e7-9786-01cbedf0fab1.png)

**Photometry Tab:**
![photometry_tab](https://user-images.githubusercontent.com/1447855/29275274-429df4b2-8113-11e7-9f90-a38606077f4f.png)

**Comment by agustrionopj** [comment]
Hi,

I've tried both multi filter and single filter for calibration but to no avail. Here is my setting for calibration (I've tried to copy yours, but it was also not working. I was using `reject=ccdclip` before copying yours).
One question, does MYRaf has some influence to any IRAF/PyRAF installation which previously installed in my laptop (or vice versa) or is it independent (i.e. it has its own settings or configuration file)? I mean, I was have a similar problem with my IRAF/PyRAF when doing zerocombine/darkcombine/flatcombine. What I did to fix it was editing `ccdred` parameter and add `ccddb$kpno/camera.dat` into `instrument` parameter in `ccdred`.

thanks

![myraf](https://user-images.githubusercontent.com/28562090/29297730-850fc7d2-8152-11e7-88fc-60bed56e16fe.png)

**Comment by agustrionopj** [comment]
In addition, I just check my camera.dat and it is already set as follows:
`exptime exptime`
`subset filter`

thanks

**Comment by yucelkilic** [comment]
Thank you for the explanation about the problem. Yes, I have to intervene in some IRAF settings during the installation process as described in #2. Because this is not MYRaf's problem. You can see the references on the #2 page. Another reason for the problem might be "instrument translation file". So, could you apply the settings (just only "2. instrument translation file" section) in the #2? 

Thank you.

**Comment by agustrionopj** [comment]
Actually, I did apply the settings as you mentioned above but it didn't work. Could it possibly caused by my IRAF/PyRAF installation path? I installed it not in the default path (i.e. `/iraf/iraf/`) but  in `/iraf/` instead. 

Nowadays, the most common (and easy) way to install IRAF/PyRAF is by using [`astroconda`](http://astroconda.readthedocs.io/en/latest/installation.html#legacy-software-stack-with-iraf) package which also give us non-standard/default installation path.

Should I reinstalled MyRAF by invoking shell script, probably to direct the installation process to correct path or something like that? 

thanks

**Comment by yucelkilic** [comment]
Maybe that's the problem stems from that. I also had a problem with the PyRAF. I fixed the problem by installing the developer version of PyRAF. Maybe you should try this version?

```
$ wget http://stsdas.stsci.edu/download/pyraf/pyraf-dev.tar.gz
$ tar -xvf pyraf-dev.tar.gz
$ cd pyraf-2.2.dev/
$ sudo python setup.py install
```

**Comment by agustrionopj** [comment]
I did :),  I also use that version in my laptop, but as you see, the problem still persist. Probably, I will try to install IRAF with default path and MyRAF on another machine to see whether the problem still there or not.
![pyraf](https://user-images.githubusercontent.com/28562090/29308164-49272ca0-8194-11e7-8714-2ffd1cea3cd3.png)

**Comment by yucelkilic** [comment]
Dear @agustrionopj 

We have fixed some bugs and we made a video for installation and usage. Maybe you want to see [the video tutorial](https://youtu.be/XVrDA8rA9hs).

Best wishes.

**Comment by agustrionopj** [comment]
Thank you! I'll try it ASAP
