### ISSUE TITLE
Install myraf

### ISSUE THREAD

**Issue by tk575** [myrafproject/myrafproject#7]
Hello, I am trying to install the program using the script for Ubuntu but when I run the program using "myraf2" the following message appears: python2.7: can not open file '/usr/share/myraf/main.py': [Errno 13] Permission denied. Running the program with: "sudo myraf2" the following message appears: Can not load MYRaf. Analyzing the installation it seems that alipy is not being installed. Any idea how to solve it?
![erro](https://user-images.githubusercontent.com/5358712/32641055-fba0cc80-c5b2-11e7-8e09-8fab25e858d8.png)

**Comment by yucelkilic** [comment]
Dear @tk575,

I have updated [installation script](https://github.com/myrafproject/myrafproject/releases). Could you please rerun installation script? If you encounter any problem please let me know.

Best wishes,
Yücel

**Comment by tk575** [comment]
Thanks @yucelkilic. I tried to install again but now the following error appears:
![myraf](https://user-images.githubusercontent.com/5358712/32700631-e37e7064-c7ae-11e7-9b5d-322472f8c5f6.png)

**Comment by yucelkilic** [comment]
Dear @tk575,

I guess you are having permission problems with .MYRaf2 directory. Could you please try following commands?

```bash
sudo rm -rf ~/.MYRaf2
myraf2
```

**Comment by yucelkilic** [comment]
Dear @tk575  

We have fixed some bugs and we made a video for installation and usage. Maybe you want to see [the video tutorial](https://youtu.be/XVrDA8rA9hs).

Here is the MYRaf 2.0's GitHub page: https://github.com/myrafproject/myrafproject2

Best wishes.

**Comment by PepeJoseHU** [comment]
Hi, i met similar problem " Can not load MYRaf."  Looks the dependence is ok and also the installation. Not sure what is the problem. Can you help me to check? what files do you need?

**Comment by yucelkilic** [comment]
Dear @PepeJoseHU,

Could you please copy the updated [main.py (https://raw.githubusercontent.com/myrafproject/myrafproject2/master/main.py) file from the myrafproject2 repository to the specified location (/usr/share/myraf/) and rewrite the error output?

`
wget https://raw.githubusercontent.com/myrafproject/myrafproject2/master/main.py
cp -rv main.py /usr/share/myraf/
myraf2
`

**Comment by PepeJoseHU** [comment]
Yes, please check the following:

Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 55, in <module>
    from myraf import Ui_Form
  File "/usr/share/myraf/myraf.py", line 3488, in <module>
    from gingawidgetFile import gingaWidget
  File "/usr/share/myraf/gingawidgetFile.py", line 13, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 51, in <module>
    ' %r, %r or %r' % (QT_API_ENV, 'pyqt', 'pyside', 'pyqt5')))
RuntimeError: Unrecognized environment variable 'pyqt4', valid values are: u'pyqt', u'pyside' or u'pyqt5'

**Comment by yucelkilic** [comment]
Could you provide information about the operating system and its version?

**Comment by PepeJoseHU** [comment]
Yes, Ubuntu 16.04 64-bit. So i follow the installation script way to install myraf2, like it in the video.

**Comment by yucelkilic** [comment]
It seems, think pyqt4 is not installed on your system. Could you try the following command again? Also, if you fail again, please do not continue with myraf2. We are working hard for myraf3. When it is complete, I will inform you to test it.

```bash
sudo apt-get update
sudo apt-get install pyqt4-dev-tools
```

**Comment by PepeJoseHU** [comment]
Thanks, it is still the same. Pity that not work here. Look forward to myraf3. Thanks for your help.
